test_superbasic:
	wsrun.pl -pipe -list superbasic.list proc_hier_pbench *.v
# 	wsrun.pl -pipe -prog loadstall.asm proc_hier_pbench *.v
# 	wsrun.pl -pipe -prog tramplefwd.asm proc_hier_pbench *.v
	#wsrun.pl -pipe -prog simplexor.asm proc_hier_pbench *.v
	#wsrun.pl -pipe -prog /u/s/w/swamit/courses/cs552/fall2021/handouts/testprograms/public/inst_tests/xor_0.asm proc_hier_pbench *.v

tests_simple:
	wsrun.pl -pipe -list simple.list proc_hier_pbench *.v
