tests_superbasic:
	wsrun.pl -pipe -list superbasic.list proc_hier_pbench *.v

tests_simple:
	wsrun.pl -pipe -list simple.list proc_hier_pbench *.v

tests_complex_pipelined:
	wsrun.pl -pipe -list complex_pipelined.list proc_hier_pbench *.v

tests_complex_pipelined_reduced:
	wsrun.pl -pipe -list complex_pipelined_reduced.list proc_hier_pbench *.v
