test_xor0:
	wsrun.pl -prog /u/s/w/swamit//courses/cs552/fall2021/handouts/testprograms/public/inst_tests/xor_0.asm proc_hier_bench *.v
# test_simple:
# 	wsrun.pl -list simple.list proc_hier_bench *.v


test_alu:
	wsrun.pl tb_alu *.v
