test_simple:
	wsrun.pl -list simple.list proc_hier_bench *.v

# test_xor:
# 	wsrun.pl -prog /u/s/w/swamit//courses/cs552/fall2021/handouts/testprograms/public/inst_tests/xor_6.asm proc_hier_bench *.v
# 	wsrun.pl -list xor.list proc_hier_bench *.v

test_alu:
	wsrun.pl tb_alu *.v
